cpus: 2
memory: 2048
http_proxy_host_port: corporate.proxy:80
https_proxy_host_port: corporate.proxy:80
no_proxy: "localhost,127.0.0.1,10.0.2.2,::1,.corporate.domain"
sync_folder_Projects: ..\\..\\..\\Projects
vagrant_user: vagrant
